[theme]
base = "dark"
primaryColor = "#10B981"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#101A34"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

