[theme]
base = "light"
primaryColor = "#4266E8"
backgroundColor = "#F4F6FF"
secondaryBackgroundColor = "#F8F9FF"
textColor = "#0A1538"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
